pub mod async_pattern;
pub mod borrow_checker_quirks;
pub mod phantom_data_covariance;
pub mod raw_pointers;
pub mod smart_pointers;
pub mod stream;
pub mod strtok;
pub mod unsafe_ways;
pub mod vector_calc_simd_vs_chunk;
